name: flutter_login
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^9.0.0
  provider: ^5.0.0
  another_transformer_page_view: ^1.0.0
  another_flushbar: ^1.10.17

  # flutter_test from sdk depends on quiver
  quiver: ^3.0.0
  pedantic: ^1.11.0

  #cupertino_icons: ^1.0.0
  # Dependency for image picker
  #image_picker: ^0.6.7+12
  # Dependency for video player
  #video_player: ^0.11.1+2
  #gallery_saver: ^2.0.3
  #firebase_auth:
  #cloud_firestore: ^0.12.9+4
  #flutter_spinkit: ^5.0.0
  #firebase_storage:
  #flutter_staggered_grid_view: ^0.3.4
  #collapsible_sidebar: ^1.0.7+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.

flutter:
  uses-material-design: true

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/images/image.png
  #  - assets/images/placeholder-logo.png
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
