name: scan4u
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  # Dependency for image picker
  image_picker: ^0.6.7+12
  # Dependency for video player
  video_player: ^0.11.1+2
  gallery_saver: ^2.0.3
  firebase_auth:
  cloud_firestore: ^0.12.9+4
  provider: ^5.0.0
  flutter_spinkit: ^5.0.0
  firebase_storage:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
